language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before_install:
  - chmod +x gradlew

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r mingu-springpjt *
  - mkdir -p deploy
  - mv mingu-springpjt.zip deploy/mingu-springpjt.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: mingu-spring-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # 파일 접근 : private
    local_dir: deploy
    wait-until-deployed: true

# CI 실행 완료시 메일 알람
notifications:
  email:
    recipients:
      - mgkang0317@gmail.com